### ISSUE TITLE
Wrong key for *-focus-search-bar

### ISSUE THREAD

**Issue by spiderbit** [walseb/exwm-firefox-core#2]
I had just problems using that function:

exwm-firefox-core-focus-search-bar

It was because of my language, because while M-d seems to work with the English browser, with German and likely many other languages it does not work it instead focus the File Pulldown menu because in German it's called "Datei" with the d so M-d triggers that.

The correct shortcut as far as I know and works at least is C-l that works 
https://www.accessfirefox.org/Firefox_Keyboard_and_Mouse_Shortcuts.html

Well both seem to be theoretically ok, but I think C-l (L) will not conflict with such a basic difference than having a different language version of the browser.

**Comment by walseb** [comment]
Thanks! Now it should be fixed!
