### ISSUE TITLE
Return to normal mode after following a link

### ISSUE THREAD

**Issue by meditans** [walseb/exwm-firefox-core#3]
Thanks for this package, it's awesome! I have just a minor inconvenience: the current definition of `exwm-firefox-core-hint-links` is:
```clojure
(defun exwm-firefox-core-hint-links ()
  "Select and open a link with your keyboard."
  (interactive)
  (exwm-input--fake-key ?\M-j)
  (exwm-firefox-evil-insert))
```
this means that when the user follows a link, the new page will be visualized in `insert-mode` and so navigation, which is the most common type of action in a new page, will be disabled until the user returns to normal state.

Would it be possible to turn back to normal state as soon as the hint has been selected?
What would be a good mechanism to do this?

**Comment by walseb** [comment]
Yes this was a problems I encountered also. One solution I believe was to have emacs open up a minibuffer prompt, wait for two keypresses then send them to firefox through fake keys. This assumes your link hint framework only has 2 keys per hint always. The more practical solution was to make the scroll functions like `C-f` and `C-b` bound in insert mode and then perhaps make them exit insert mode when pressed. The proper solution requires firefox to trigger the exit to normal state function which I don't think is possible without modifying the source code of firefox.

**Comment by meditans** [comment]
I see, unfortunately expecting 2 keys per hint would break hint filtering, which is vital for me. Is there some kind of hook that we could use from the exwm side instead? Like, could `exwm-update-title-hook` be enough?

**Comment by walseb** [comment]
> exwm-update-title-hook

That's a great idea, I never considered that.

**Comment by meditans** [comment]
Well, I fear it could be a little unstable, depending on when that hook is actually called. The other possibility I had in mind is setting a buffer local variable when we begin the hint process (we control that part) and then hook to `exwm-input--event-hook` a function that checks `last-command-event` and sees if it's a `return`. In that case we go back to normal mode.

**Comment by walseb** [comment]
Yes that's a good idea aswell. I think simplest is to add a function to `exwm-update-title-hook` inside the hint link function that both removes itself from `exwm-update-title-hook` when triggered and enters evil normal state. Perhaps you could cover the case where the user cancels the link hint using `exwm-input--event-hook` but I don't see any issues. I like using link hints where you don't have to press `return` to confirm the selection but in that case checking for `return` might be even simpler.

**Comment by meditans** [comment]
So, the problem is that none of those suggestions work quite right:
- waiting for `exwm-update-title-hook` has the problem that the title doesn't change in a link that points to the same page (like the links in https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Introduction). So I'm not sure that this is a viable solution after all.
- waiting for `exwm-input--event-hook` has the problem that, once emacs delegates the input to firefox, `last-command-event` will not pick the actual characters written, and so we're unable to see when `<return>` has been pressed. A workaround here could be not relinquishing control to firefox, but instead feeding the characters one at a time, so that we can check when we have a solution.

I wish I had a cleaner solution, though.

**Comment by walseb** [comment]
I see. Actually I remember now that I made this PR way back https://github.com/ch11ng/exwm/pull/598
It updates `exwm-input-send-next-key` so that it accepts a termination character. A solution to the problem might be (pseudo code):
```lisp
(defun exwm-firefox-core-hint-links ()
  (exwm-input--fake-key ?\M-j)
  (exwm-input-send-next-key 999 'return) 
  (exwm-input--fake-key 'return))
``` 
That way you you never need to enter into insert mode in the first place.

**Comment by walseb** [comment]
I don't remember if using that function actually fixed my link hinting issues.

**Comment by meditans** [comment]
Thank you for the stub you provided before; it didn't work in a way that I liked, but it spurred me to write a version that I like:

```clojure
(defun med/exwm-firefox-core-hint-links ()
    (interactive)
    (exwm-input--fake-key ?\M-j)
    (message "Following link")
    (let ((exwm-input-line-mode-passthrough t)
          (still-filtering t))
      (catch 'break
        (while t
          (let ((k (read-key)))
            (cond
             ;; Enter
             ((eq k 13) (progn (exwm-input--fake-key 'return)
                               (throw 'break nil)))
             ;; ESC
             ((eq k 27) (progn (exwm-input--fake-key 'escape)
                               (throw 'break nil)))
             ;; A number
             ((<= 48 k 57) (progn (exwm-input--fake-key k)
                                  (setq still-filtering nil)))
             ;; A character, and we're still filtering
             (still-filtering (exwm-input--fake-key k))
             ;; Otherwise
             (t (progn (push k unread-command-events)
                       (throw 'break nil))))))))
    (message "Followed link"))
```
Now, I'm not an elisp expert, so if you have any advice on the code, please share. Otherwise feel free to close this issue, thanks again :relaxed:!

**Comment by walseb** [comment]
Great, you are welcome! In regards to the code I'm not an expert either, but I might replace the use of exceptions with a termination variable or separate that cond into a function that returns the key to fake tupled with a termination bool and the still-filtering variable. Or maybe use the nil value of key to signify termination. But I think it's more than clear enough as it is now with exceptions.
